package output

import (
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"
	"time"

	"govibe/pkg/models"
)

// HTMLWriter handles HTML file output
type HTMLWriter struct {
	outputDir string
	domain    string
}

// NewHTMLWriter creates a new HTML writer
func NewHTMLWriter(outputDir, domain string) *HTMLWriter {
	return &HTMLWriter{
		outputDir: outputDir,
		domain:    domain,
	}
}

const htmlTemplate = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.Title}} - {{.Domain}}</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
            margin: 0; padding: 20px;
            background-color: #1a1a2e; color: #eee;
            max-width: 100%; overflow-x: hidden;
        }
        h1, h2 { color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 10px; }
        .table-wrapper { width: 100%; overflow-x: auto; margin: 20px 0; }
        table { border-collapse: collapse; width: 100%; background-color: #16213e; font-size: 13px; table-layout: fixed; }
        th, td { border: 1px solid #0f3460; padding: 8px 10px; text-align: left; vertical-align: top; word-wrap: break-word; overflow-wrap: break-word; }
        th { background-color: #0f3460; color: #00d4ff; font-weight: 600; position: sticky; top: 0; z-index: 10; }
        tr:nth-child(even) { background-color: #1a1a40; }
        tr:hover { background-color: #0f3460; }
        tr.hidden { display: none; }
        .enabled { color: #00ff88; }
        .disabled { color: #ff4757; }
        .account-flags { min-width: 220px; width: 14%; white-space: nowrap; }
        .member-cell { width: 20%; min-width: 200px; }
        .sid { font-family: monospace; font-size: 11px; color: #888; min-width: 320px; width: 18%; }
        th { cursor: pointer; user-select: none; }
        th:hover { background-color: #1a3a5c; }
        th.sort-asc::after { content: ' ▲'; font-size: 10px; }
        th.sort-desc::after { content: ' ▼'; font-size: 10px; }
        .nav { background-color: #0f3460; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .nav a { color: #00d4ff; text-decoration: none; margin-right: 20px; padding: 5px 10px; border-radius: 3px; }
        .nav a:hover { background-color: #16213e; }
        .count { color: #00ff88; font-size: 0.9em; }
        .filter-box { margin: 15px 0; padding: 10px; background-color: #0f3460; border-radius: 5px; display: flex; align-items: center; gap: 15px; flex-wrap: wrap; }
        .filter-wrap { position: relative; display: inline-block; }
        .filter-wrap input[type="text"] { padding: 8px 30px 8px 12px; width: 300px; border: 1px solid #00d4ff; border-radius: 3px; background-color: #16213e; color: #eee; font-size: 14px; }
        .filter-wrap input[type="text"]:focus { outline: none; box-shadow: 0 0 5px #00d4ff; }
        .filter-wrap .clear-btn { position: absolute; right: 8px; top: 50%; transform: translateY(-50%); background: none; border: none; color: #888; font-size: 16px; cursor: pointer; padding: 0 4px; display: none; }
        .filter-wrap .clear-btn:hover { color: #ff4757; }
        .filter-wrap.has-text .clear-btn { display: block; }
        .filter-box span { color: #888; }
        .filter-box button { padding: 8px 14px; border: 1px solid #00d4ff; border-radius: 3px; background-color: #16213e; color: #00d4ff; font-size: 13px; cursor: pointer; }
        .filter-box button:hover { background-color: #0f3460; }
        .filter-box button.active { background-color: #00d4ff; color: #1a1a2e; }
        .flag { display: inline-block; padding: 2px 6px; margin: 1px; border-radius: 3px; font-size: 11px; background-color: #0f3460; }
        .flag.warn { background-color: #ff6b35; color: #fff; }
        .flag.danger { background-color: #ff4757; color: #fff; }
        footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #0f3460; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="nav">
        <a href="{{.Domain}}_users.html">Users</a>
        <a href="{{.Domain}}_groups.html">Groups</a>
        <a href="{{.Domain}}_computers.html">Computers</a>
        <a href="{{.Domain}}_spns.html">SPNs</a>
        <a href="{{.Domain}}_policy.html">Password Policy</a>
        <a href="{{.Domain}}_index.html">Overview</a>
    </div>
    <h1>{{.Title}}</h1>
    <p class="count">Total: {{.Count}} entries</p>
    <div class="filter-box">
        <div class="filter-wrap" id="filterWrap">
            <input type="text" id="filterInput" placeholder="Filter results..." autocomplete="off">
            <button type="button" class="clear-btn" id="clearFilter">&times;</button>
        </div>
        {{.ExtraControls}}
        <span id="filterStatus"></span>
    </div>
    {{.Content}}
    <footer>Generated by GoVibe on {{.GeneratedAt}}</footer>
    <script>
        (function() {
            var input = document.getElementById('filterInput');
            var filterWrap = document.getElementById('filterWrap');
            var clearBtn = document.getElementById('clearFilter');
            var status = document.getElementById('filterStatus');
            var table = document.querySelector('table');
            var tbody = table ? table.querySelector('tbody') : null;
            var rows = tbody ? Array.from(tbody.querySelectorAll('tr')) : [];
            var headers = table ? table.querySelectorAll('thead th') : [];
            var timeout = null;
            var total = rows.length;
            var hideDisabled = localStorage.getItem('hideDisabled') === 'true';
            var savedSort = JSON.parse(localStorage.getItem('sortState') || '{"col":-1,"asc":true}');
            var currentSort = savedSort;

            function updateClearBtn() {
                filterWrap.classList.toggle('has-text', input.value.length > 0);
            }

            function applyFilters() {
                var filter = input.value.toLowerCase();
                var shown = 0;
                for (var i = 0; i < rows.length; i++) {
                    var text = rows[i].textContent.toLowerCase();
                    var matchText = !filter || text.indexOf(filter) > -1;
                    var matchDisabled = !hideDisabled || text.indexOf('disabled') === -1;
                    var visible = matchText && matchDisabled;
                    rows[i].classList.toggle('hidden', !visible);
                    if (visible) shown++;
                }
                status.textContent = (filter || hideDisabled) ? ('Showing ' + shown + ' of ' + total) : '';
                updateClearBtn();
            }

            function sortTable(colIndex, skipSave) {
                if (currentSort.col === colIndex) {
                    currentSort.asc = !currentSort.asc;
                } else {
                    currentSort.col = colIndex;
                    currentSort.asc = true;
                }

                if (!skipSave) {
                    localStorage.setItem('sortState', JSON.stringify(currentSort));
                }

                headers.forEach(function(h, i) {
                    h.classList.remove('sort-asc', 'sort-desc');
                    if (i === colIndex) {
                        h.classList.add(currentSort.asc ? 'sort-asc' : 'sort-desc');
                    }
                });

                rows.sort(function(a, b) {
                    var aVal = a.cells[colIndex] ? a.cells[colIndex].textContent.trim().toLowerCase() : '';
                    var bVal = b.cells[colIndex] ? b.cells[colIndex].textContent.trim().toLowerCase() : '';
                    var aNum = parseFloat(aVal);
                    var bNum = parseFloat(bVal);
                    if (!isNaN(aNum) && !isNaN(bNum)) {
                        return currentSort.asc ? aNum - bNum : bNum - aNum;
                    }
                    if (aVal < bVal) return currentSort.asc ? -1 : 1;
                    if (aVal > bVal) return currentSort.asc ? 1 : -1;
                    return 0;
                });

                rows.forEach(function(row) { tbody.appendChild(row); });
                applyFilters();
            }

            headers.forEach(function(header, index) {
                header.addEventListener('click', function() { sortTable(index); });
            });

            input.addEventListener('input', function() {
                clearTimeout(timeout);
                status.textContent = 'Filtering...';
                timeout = setTimeout(applyFilters, 300);
            });

            clearBtn.addEventListener('click', function() {
                input.value = '';
                applyFilters();
                input.focus();
            });

            var hideBtn = document.getElementById('hideDisabledBtn');
            if (hideBtn) {
                if (hideDisabled) {
                    hideBtn.classList.add('active');
                    hideBtn.textContent = 'Show Disabled';
                }
                hideBtn.addEventListener('click', function() {
                    hideDisabled = !hideDisabled;
                    localStorage.setItem('hideDisabled', hideDisabled);
                    hideBtn.classList.toggle('active', hideDisabled);
                    hideBtn.textContent = hideDisabled ? 'Show Disabled' : 'Hide Disabled';
                    applyFilters();
                });
            }

            // Restore saved sort on page load
            if (currentSort.col >= 0 && currentSort.col < headers.length) {
                currentSort.asc = !currentSort.asc; // Toggle because sortTable will toggle back
                sortTable(currentSort.col, true);
            } else {
                applyFilters();
            }
        })();
    </script>
    {{.ExtraScript}}
</body>
</html>`

// WriteAll writes all domain data to HTML files
func (w *HTMLWriter) WriteAll(data *models.DomainData) error {
	if err := os.MkdirAll(w.outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := w.writeUsers(data.Users); err != nil {
		return err
	}
	if err := w.writeGroups(data.Groups); err != nil {
		return err
	}
	if err := w.writeComputers(data.Computers); err != nil {
		return err
	}
	if err := w.writeSPNs(data.SPNs); err != nil {
		return err
	}
	if err := w.writePasswordPolicy(data.PasswordPolicy, data.FGPolicies); err != nil {
		return err
	}
	if err := w.writeIndex(data); err != nil {
		return err
	}

	return nil
}

type htmlData struct {
	Title         string
	Domain        string
	Count         int
	Content       template.HTML
	ExtraControls template.HTML
	ExtraScript   template.HTML
	GeneratedAt   string
}

func (w *HTMLWriter) writeHTMLFile(filename string, data htmlData) error {
	path := filepath.Join(w.outputDir, fmt.Sprintf("%s_%s.html", w.domain, filename))

	tmpl, err := template.New("html").Parse(htmlTemplate)
	if err != nil {
		return err
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create %s: %w", path, err)
	}
	defer file.Close()

	data.Domain = w.domain
	data.GeneratedAt = time.Now().Format("2006-01-02 15:04:05")

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}

	fmt.Printf("[+] Saved: %s\n", path)
	return nil
}

func (w *HTMLWriter) writeUsers(users []models.User) error {
	var sb strings.Builder
	sb.WriteString(`<div class="table-wrapper"><table>
<thead><tr><th>Username</th><th>Status</th><th class="account-flags">Account Flags</th><th>Password Last Set</th><th>Last Logon</th><th>Primary Group</th><th class="member-cell">Member Of</th><th>Description</th><th>Home Directory</th><th class="sid">SID</th></tr></thead><tbody>`)

	for _, user := range users {
		status := `<span class="enabled">Enabled</span>`
		if !user.Enabled {
			status = `<span class="disabled">Disabled</span>`
		}

		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td class="member-cell">%s</td><td>%s</td><td>%s</td><td class="sid">%s</td></tr>`,
			escapeHTML(user.Username),
			status,
			formatAccountFlags(user.AccountSettings),
			formatTimestamp(user.PasswordLastSet),
			formatTimestamp(user.LastLogon),
			escapeHTML(user.PrimaryGroup),
			formatListCompact(user.MemberOf),
			escapeHTML(user.Description),
			escapeHTML(user.HomeDirectory),
			escapeHTML(user.SID),
		))
	}

	sb.WriteString("</tbody></table></div>")

	return w.writeHTMLFile("users", htmlData{
		Title:         "Domain Users",
		Count:         len(users),
		Content:       template.HTML(sb.String()),
		ExtraControls: template.HTML(`<button id="hideDisabledBtn">Hide Disabled</button>`),
	})
}

func (w *HTMLWriter) writeGroups(groups []models.Group) error {
	var sb strings.Builder
	sb.WriteString(`<div class="table-wrapper"><table>
<thead><tr><th>Name</th><th>Description</th><th class="member-cell">Member Of</th><th class="member-cell">Members</th><th class="sid">SID</th></tr></thead><tbody>`)

	for _, group := range groups {
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td class="member-cell">%s</td><td class="member-cell">%s</td><td class="sid">%s</td></tr>`,
			escapeHTML(group.Name),
			escapeHTML(group.Description),
			formatListCompact(group.MemberOf),
			formatListCompact(group.Members),
			escapeHTML(group.SID),
		))
	}

	sb.WriteString("</tbody></table></div>")

	return w.writeHTMLFile("groups", htmlData{
		Title:   "Domain Groups",
		Count:   len(groups),
		Content: template.HTML(sb.String()),
	})
}

func (w *HTMLWriter) writeComputers(computers []models.Computer) error {
	var sb strings.Builder
	sb.WriteString(`<div class="table-wrapper"><table>
<thead><tr><th>Name</th><th>DNS Hostname</th><th>Description</th><th>Operating System</th><th>OS Version</th><th>Last Logon</th><th class="member-cell">Member Of</th><th class="sid">SID</th></tr></thead><tbody>`)

	for _, computer := range computers {
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td class="member-cell">%s</td><td class="sid">%s</td></tr>`,
			escapeHTML(computer.Name),
			escapeHTML(computer.DNSHostName),
			escapeHTML(computer.Description),
			escapeHTML(computer.OperatingSystem),
			escapeHTML(computer.OSVersion),
			formatTimestamp(computer.LastLogonTimestamp),
			formatListCompact(computer.MemberOf),
			escapeHTML(computer.SID),
		))
	}

	sb.WriteString("</tbody></table></div>")

	return w.writeHTMLFile("computers", htmlData{
		Title:   "Domain Computers",
		Count:   len(computers),
		Content: template.HTML(sb.String()),
	})
}

func (w *HTMLWriter) writeSPNs(spns []models.SPN) error {
	var sb strings.Builder
	sb.WriteString(`<div class="table-wrapper"><table>
<thead><tr><th>Service Principal Name</th><th>Username</th><th>Description</th><th>Password Last Set</th><th class="member-cell">Member Of</th></tr></thead><tbody>`)

	for _, spn := range spns {
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td class="member-cell">%s</td></tr>`,
			escapeHTML(spn.ServicePrincipalName),
			escapeHTML(spn.Username),
			escapeHTML(spn.Description),
			formatTimestamp(spn.PasswordLastSet),
			formatListCompact(spn.MemberOf),
		))
	}

	sb.WriteString("</tbody></table></div>")

	return w.writeHTMLFile("spns", htmlData{
		Title:   "Kerberoastable Accounts (SPNs)",
		Count:   len(spns),
		Content: template.HTML(sb.String()),
	})
}

func (w *HTMLWriter) writePasswordPolicy(policy models.PasswordPolicy, fgpp []models.FineGrainedPasswordPolicy) error {
	var sb strings.Builder

	sb.WriteString("<h2>Domain Password Policy</h2>")
	sb.WriteString(`<div class="table-wrapper"><table><thead><tr><th>Setting</th><th>Value</th></tr></thead><tbody>`)
	sb.WriteString(fmt.Sprintf(`<tr><td>Minimum Password Length</td><td>%d characters</td></tr>`, policy.MinPasswordLength))
	sb.WriteString(fmt.Sprintf(`<tr><td>Lockout Threshold</td><td>%d attempts</td></tr>`, policy.LockoutThreshold))
	sb.WriteString(fmt.Sprintf(`<tr><td>Lockout Duration</td><td>%d minutes</td></tr>`, policy.LockoutDuration))
	sb.WriteString(fmt.Sprintf(`<tr><td>Password History</td><td>%d passwords remembered</td></tr>`, policy.PasswordsRemembered))
	sb.WriteString(fmt.Sprintf(`<tr><td>Password Properties</td><td>%s</td></tr>`, formatList(policy.PasswordProperties)))
	sb.WriteString("</tbody></table></div>")

	if len(fgpp) > 0 {
		sb.WriteString("<h2>Fine-Grained Password Policies</h2>")
		sb.WriteString(`<div class="table-wrapper"><table><thead><tr><th>Name</th><th>Min Length</th><th>Lockout Threshold</th><th>Lockout Duration</th><th>History</th><th>Complexity</th><th class="member-cell">Applies To</th></tr></thead><tbody>`)
		for _, fg := range fgpp {
			complexity := "No"
			if fg.PasswordComplexity {
				complexity = "Yes"
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%d</td><td>%d</td><td>%d minutes</td><td>%d</td><td>%s</td><td class="member-cell">%s</td></tr>`,
				escapeHTML(fg.Name), fg.MinPasswordLength, fg.LockoutThreshold, fg.LockoutDuration, fg.PasswordsRemembered, complexity, formatList(fg.AppliesTo)))
		}
		sb.WriteString("</tbody></table></div>")
	}

	return w.writeHTMLFile("policy", htmlData{
		Title:   "Password Policies",
		Count:   1 + len(fgpp),
		Content: template.HTML(sb.String()),
	})
}

func (w *HTMLWriter) writeIndex(data *models.DomainData) error {
	var sb strings.Builder

	sb.WriteString("<h2>Domain Information</h2>")
	sb.WriteString(`<div class="table-wrapper"><table><thead><tr><th>Property</th><th>Value</th></tr></thead><tbody>`)
	sb.WriteString(fmt.Sprintf(`<tr><td>Domain Name</td><td>%s</td></tr>`, escapeHTML(data.Domain.Name)))
	sb.WriteString(fmt.Sprintf(`<tr><td>Domain SID</td><td class="sid">%s</td></tr>`, escapeHTML(data.Domain.DomainSID)))
	sb.WriteString(fmt.Sprintf(`<tr><td>Functional Level</td><td>%s</td></tr>`, escapeHTML(data.Domain.FunctionalLevel)))
	sb.WriteString("</tbody></table></div>")

	sb.WriteString("<h2>Statistics</h2>")
	sb.WriteString(`<div class="table-wrapper"><table><thead><tr><th>Object Type</th><th>Count</th></tr></thead><tbody>`)
	sb.WriteString(fmt.Sprintf(`<tr><td><a href="%s_users.html">Users</a></td><td>%d</td></tr>`, w.domain, len(data.Users)))
	sb.WriteString(fmt.Sprintf(`<tr><td><a href="%s_groups.html">Groups</a></td><td>%d</td></tr>`, w.domain, len(data.Groups)))
	sb.WriteString(fmt.Sprintf(`<tr><td><a href="%s_computers.html">Computers</a></td><td>%d</td></tr>`, w.domain, len(data.Computers)))
	sb.WriteString(fmt.Sprintf(`<tr><td><a href="%s_spns.html">Kerberoastable Accounts</a></td><td>%d</td></tr>`, w.domain, len(data.SPNs)))

	enabled, disabled := 0, 0
	for _, u := range data.Users {
		if u.Enabled {
			enabled++
		} else {
			disabled++
		}
	}
	sb.WriteString(fmt.Sprintf(`<tr><td>Enabled Users</td><td>%d</td></tr>`, enabled))
	sb.WriteString(fmt.Sprintf(`<tr><td>Disabled Users</td><td>%d</td></tr>`, disabled))
	sb.WriteString("</tbody></table></div>")

	if len(data.Trusts) > 0 {
		sb.WriteString("<h2>Domain Trusts</h2>")
		sb.WriteString(`<div class="table-wrapper"><table><thead><tr><th>Target Domain</th><th>Trust Type</th><th>Direction</th></tr></thead><tbody>`)
		for _, t := range data.Trusts {
			sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td></tr>`, escapeHTML(t.TargetDomain), escapeHTML(t.TrustType), escapeHTML(t.TrustDirection)))
		}
		sb.WriteString("</tbody></table></div>")
	}

	return w.writeHTMLFile("index", htmlData{
		Title:   "Domain Overview",
		Count:   len(data.Users) + len(data.Groups) + len(data.Computers),
		Content: template.HTML(sb.String()),
	})
}

// Helper functions

func escapeHTML(s string) string {
	return template.HTMLEscapeString(s)
}

func formatListCompact(items []string) string {
	if len(items) == 0 {
		return "-"
	}
	var escaped []string
	for _, item := range items {
		escaped = append(escaped, escapeHTML(item))
	}
	return strings.Join(escaped, ", ")
}

func formatTimestamp(t time.Time) string {
	if t.IsZero() || t.Year() < 1970 {
		return "Never"
	}
	return t.Format("2006-01-02 15:04:05")
}

func formatAccountFlags(flags []string) string {
	if len(flags) == 0 {
		return "-"
	}

	dangerFlags := map[string]bool{
		"ACCOUNT_DISABLED": true,
		"ACCOUNT_LOCKED":   true,
		"PASSWORD_EXPIRED": true,
		"DONT_REQ_PREAUTH": true,
	}

	warnFlags := map[string]bool{
		"PASSWD_NOTREQD":         true,
		"DONT_EXPIRE_PASSWD":     true,
		"TRUSTED_FOR_DELEGATION": true,
	}

	var parts []string
	for _, flag := range flags {
		class := "flag"
		if dangerFlags[flag] {
			class = "flag danger"
		} else if warnFlags[flag] {
			class = "flag warn"
		}
		parts = append(parts, fmt.Sprintf(`<span class="%s">%s</span>`, class, escapeHTML(flag)))
	}
	return strings.Join(parts, " ")
}

func formatList(items []string) string {
	return formatListCompact(items)
}
